Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda with AWS S3

Resources:
  AWSLambdaWithS3:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python:3.9
      PackageType: Image
      Timeout: 600
      MemorySize: 1024
      Environment:
        Variables:
          SLACK_CHANNEL_ID: SLACK_CHANNEL_ID
          SLACK_BOT_TOKEN: SLACK_BOT_TOKEN
          AWS_REGION: AWS_REGION
          AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
          AWS_ENDPOINT_URL: AWS_ENDPOINT_URL
          AWS_S3_BUCKET_NAME: AWS_S3_BUCKET_NAME
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket:
              Ref: AWS_S3_BUCKET_NAME
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .jpeg

    Metadata:
      Dockerfile: ./dockerfiles/Dockerfile
      DockerContext: .
